name: Publish Blog Post

on:
  push:
    paths:
      - 'blogs/**'  # Trigger on changes to files in the blogs directory
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch new blog content
        run: node fetch-blog-content.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Add new blog post'
          git push
